name: publish to pypi
inputs:
  token:
    description: PuPi token.
    required: true
  path:
    description: 'Path to the package to publish'
    required: true
  publish:
    description: 'Set to true to actually publish'
    required: true
    default: 'false'
runs:
  using: 'composite'
  steps:
    - if: ${{ inputs.publish == 'true' }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - if: ${{ inputs.publish == 'true' }}
      shell: bash
      run: |
        cd ${{ inputs.path }} && \
        echo "publishing python implementation at " ${{ inputs.path }}
        pip install uv build twine && \
        python -m build
    - if: ${{ inputs.publish == 'true' }}
      shell: bash
      run: |
        cd ${{ inputs.path }} && \
        python -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ inputs.token }}
    - shell: bash
      run: echo "published=" ${{ inputs.publish == 'true' }} >> $GITHUB_OUTPUT

  
