name: publish to npm
inputs:
  token:
    description: NPM token.
    required: true
  path:
    description: 'Path to the package to publish'
    required: true
  publish:
    description: 'Set to true to actually publish'
    required: true
    default: 'false'
runs:
  using: 'composite'
  steps:
    - if: ${{ inputs.publish == 'true' }}
      uses: actions/setup-node@v4
      with:
        node-version: 21
        registry-url: https://registry.npmjs.org/
    - if: ${{ inputs.publish == 'true' }}
      shell: bash
      run: |
        cd ${{ inputs.path }} && \
        echo "publishing typescript implementation" at ${{ inputs.path }} && \
        npm i -D && \
        npm run build
    - if: ${{ inputs.publish == 'true' }}
      shell: bash
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
    - shell: bash
      run: echo "published=" ${{ inputs.publish == 'true' }} >> $GITHUB_OUTPUT

  
